### ISSUE TITLE
зачем?

### ISSUE THREAD

**Issue by isinkin** [DavidErbaev/vk-io-longpoll#1]
зачем был создан этот модуль?

**Comment by DavidErbaev** [comment]
Hi my friend, this module was created by fan, I just did not think of anything and I have done so far that one function of automatic configuration of LongPoll, and in the future it will be supplemented. I can't tell you what will happen in the future, I'm sorry.

**Comment by DavidErbaev** [comment]
> зачем был создан этот модуль?

Hi my friend, this module was created by fan, I just did not think of anything and I have done so far that one function of automatic configuration of LongPoll, and in the future it will be supplemented. I can't tell you what will happen in the future, I'm sorry.
